name: rtnerf
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy=1.22.3
  - scikit-image=0.17.2
  - scipy=1.7.3
  - matplotlib=3.5.1
  - tqdm=4.64.0
  - pip:
    - dotmap==1.3.30
    - imageio==2.19.3
    - imageio-ffmpeg==0.4.7
    - ipdb==0.13.9
    - lpips==0.1.4
    - opencv-python==4.6.0.66
    - pretrainedmodels==0.7.4
    - pyhocon==0.3.59
    - tensorboard==2.9.1
    - torchinfo
